import type { Metadata } from 'next'
import { Container, Box } from '@mui/material'
import { ReactNode } from 'react'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <Container fixed>
        <Box sx={{ height: '100vh' }} mt={10}>{children}</Box>
      </Container>
      </body>
    </html>
  )
}
